"""Disposable, local-only GTK fixture for desktop acceptance tests. No files or network."""
import gi
import sys
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GLib

GLib.set_prgname('bridge-desktop-test')
GLib.set_application_name('Bridge Desktop Test')
window = Gtk.Window(title='Bridge Desktop Test')
window.set_default_size(520, 440)
box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=12)
box.set_border_width(20)
window.add(box)
label = Gtk.Label(label='Bridge desktop test: ready')
box.pack_start(label, False, False, 0)
entry = Gtk.Entry()
entry.get_accessible().set_name('Test name')
entry.set_placeholder_text('Test name')
box.pack_start(entry, False, False, 0)
button = Gtk.Button(label='Apply test')
button.connect('clicked', lambda _: label.set_text('Applied: ' + entry.get_text()))
box.pack_start(button, False, False, 0)
check = Gtk.CheckButton(label='Test checkbox')
box.pack_start(check, False, False, 0)
scale = Gtk.Scale.new_with_range(Gtk.Orientation.HORIZONTAL, 0, 100, 1)
scale.get_accessible().set_name('Test slider')
box.pack_start(scale, False, False, 0)
scroller = Gtk.ScrolledWindow()
scroller.set_min_content_height(150)
scroller.set_max_content_height(150)
scroller.set_propagate_natural_height(True)
listbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
for n in range(30):
    listbox.pack_start(Gtk.Label(label=f'Test row {n + 1}'), False, False, 0)
scroller.add(listbox)
box.pack_start(scroller, False, False, 0)
scroller.get_vadjustment().connect('value-changed', lambda adjustment: label.set_text(f'Scroll position: {int(adjustment.get_value())}'))
window.connect('destroy', Gtk.main_quit)
window.show_all()
if '--fullscreen' in sys.argv:
    window.fullscreen()
window.present()
GLib.timeout_add_seconds(1200, lambda: (Gtk.main_quit(), False)[1])
Gtk.main()
